[tool.poetry]
name = "heunstep"
version = "0.1.0"
description = ""
authors = ["KangWon LEE <kangwon.lee.edu@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
